services:
  backend:
    build:
      context: .               # 👈 now it's the root folder
      dockerfile: backend/Dockerfile
    container_name: sentiment-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sentiment-frontend
    ports:
      - "3000:3000"
    command: npm run dev -- --host
